name: Check and Build
env:
  kernel_repository: LXJ200625/kernel_xiaomi_dipper_bpf
  kernel_branch: main
  device: dipper
  clang_version: r416183b
  defconfig: |
    dipper-perf_defconfig
  kernel_patch: |
    backport-path-umount.patch
  kernelsu_patch: |
on:
  workflow_dispatch:
    inputs:
      allow_rebuild:
        description: "Allow Rebuild"
        type: boolean
        default: false
jobs:
  check_kernelsu_update:
    name: Check KernelSU update
    runs-on: ubuntu-latest
    steps:
      - name: Check KernelSU version
        id: check_kernelsu_version
        run: |
          local_version=$(curl -L --header 'authorization: Bearer ${{ github.token }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name || echo "v0.0.0")
          remote_version=v0.9.5
          echo local_version=$local_version
          echo remote_version=$remote_version
    outputs:
      local_version: ${{ steps.check_kernelsu_version.outputs.local_version }}
      remote_version: ${{ steps.check_kernelsu_version.outputs.remote_version }}
  build:
    name: Build kernel
    needs: check_kernelsu_update
    if: inputs.allow_rebuild || needs.check_kernelsu_update.outputs.local_version != needs.check_kernelsu_update.outputs.remote_version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set env
        run: |
          echo kernelsu_remote_version=${{ needs.check_kernelsu_update.outputs.remote_version }} >> $GITHUB_ENV
          if [[ "$clang_version" = r* || "$clang_version" = "latest" ]]; then
              echo clang_type=aosp >> $GITHUB_ENV
          else
              echo clang_type=vanilla >> $GITHUB_ENV
          fi
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y --no-install-recommends \
              binutils-arm-linux-gnueabi \
              binutils-aarch64-linux-gnu \
              gcc-arm-linux-gnueabi \
              gcc-aarch64-linux-gnu \
              libc6-dev-armhf-cross \
              make git flex bison libssl-dev bc libelf-dev
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: ${{ env.kernel_repository }}
          ref: ${{ env.kernel_branch }}
          submodules: recursive
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: this-repo
      - name: Get latest kernel commit id
        run: echo kernel_commit_id=$(git rev-parse HEAD) >> $GITHUB_ENV
      - name: Merge defconfig
        run: |
          > arch/arm64/configs/merged_defconfig
          while read -r line; do
              if [ -z "$line" ] || [[ "$line" == "#"* ]]; then
                  continue
              fi
              cat arch/arm64/configs/$line >> arch/arm64/configs/merged_defconfig
          done <<<"$defconfig"
          echo 'CONFIG_VDSO32=n' >> arch/arm64/configs/merged_defconfig
      - name: Setup KernelSU
        run: |
          curl -L https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh | bash -s -- $kernelsu_remote_version
          echo 'CONFIG_KPROBES=y' >> arch/arm64/configs/merged_defconfig
          echo 'CONFIG_HAVE_KPROBES=y' >> arch/arm64/configs/merged_defconfig
          echo 'CONFIG_KPROBE_EVENTS=y' >> arch/arm64/configs/merged_defconfig
      - name: Apply kernel patch
        run: |
          while read -r line; do
              if [ -z "$line" ] || [[ "$line" == "#"* ]]; then
                  continue
              fi
              git apply "this-repo/patches/$line" || true
          done <<<"$kernel_patch"
      - name: Apply KernelSU patch
        run: |
          while read -r line; do
              if [ -z "$line" ] || [[ "$line" == "#"* ]]; then
                  continue
              fi
              git apply -p2 --directory KernelSU/kernel "this-repo/patches/$line" || true
          done <<<"$kernelsu_patch"
      - name: AOSP-Clang Setup
        run: |
          mkdir -p aosp-clang
          curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r416183b.tar.gz | tar -xz -C aosp-clang
          echo PATH=$(pwd)/aosp-clang/bin:$PATH >> $GITHUB_ENV
      - name: Export flags
        run: |
          echo 'flags=O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-' >> $GITHUB_ENV
      - name: Make defconfig
        run: make $flags merged_defconfig
      - name: Make
        run: make $flags -j$(nproc --all) Image.gz-dtb
      - name: AnyKernel3
        run: |
          curl -Lo AnyKernel3.zip https://github.com/osm0sis/AnyKernel3/archive/refs/heads/master.zip
          unzip -q AnyKernel3.zip
          cat >AnyKernel3-master/anykernel.sh <<EOF
          properties() {
              kernel.string=dipper-kernel-KSU
              do.devicecheck=1
              do.modules=0
              do.cleanup=1
              do.cleanuponabort=1
              device.name1=dipper
          }
          block=auto
          is_slot_device=auto
          . tools/ak3-core.sh
          split_boot
          flash_boot
          EOF
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3-master/
          cd AnyKernel3-master
          zip -r -q ../boot.zip *
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot
          path: boot.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.kernelsu_remote_version }}
          body: |
            Device: dipper
            Kernel: ${{ github.sha }}
            KernelSU: v0.9.5
          files: boot.zip
